version: '3'
services:
  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    depends_on:
      - jaeger
      - zipkin

  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "14268:14268"  # Collector HTTP
      - "16686:16686"  # UI

  # Zipkin
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"   # API and UI 