# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mcp_sync.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'mcp_sync.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emcp_sync.proto\x12\x08mcp.sync\"\xb4\x02\n\rContextChange\x12=\n\x0eoperation_type\x18\x01 \x01(\x0e\x32%.mcp.sync.ContextChange.OperationType\x12\x12\n\ncontext_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\tparent_id\x18\x04 \x01(\t\x12\x1c\n\x14\x63reated_at_unix_secs\x18\x05 \x01(\x03\x12\x1c\n\x14updated_at_unix_secs\x18\x06 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x07 \x01(\x0c\x12\x10\n\x08metadata\x18\x08 \x01(\x0c\"S\n\rOperationType\x12\x1e\n\x1aOPERATION_TYPE_UNSPECIFIED\x10\x00\x12\n\n\x06\x43REATE\x10\x01\x12\n\n\x06UPDATE\x10\x02\x12\n\n\x06\x44\x45LETE\x10\x03\"l\n\x0bSyncRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x1a\n\x12last_known_version\x18\x02 \x01(\x04\x12.\n\rlocal_changes\x18\x03 \x03(\x0b\x32\x17.mcp.sync.ContextChange\"\x87\x01\n\x0cSyncResponse\x12\x1e\n\x16\x63urrent_server_version\x18\x01 \x01(\x04\x12/\n\x0eremote_changes\x18\x02 \x03(\x0b\x32\x17.mcp.sync.ContextChange\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x15\n\rerror_message\x18\x04 \x01(\t2D\n\x0bSyncService\x12\x35\n\x04Sync\x12\x15.mcp.sync.SyncRequest\x1a\x16.mcp.sync.SyncResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mcp_sync_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTEXTCHANGE']._serialized_start=29
  _globals['_CONTEXTCHANGE']._serialized_end=337
  _globals['_CONTEXTCHANGE_OPERATIONTYPE']._serialized_start=254
  _globals['_CONTEXTCHANGE_OPERATIONTYPE']._serialized_end=337
  _globals['_SYNCREQUEST']._serialized_start=339
  _globals['_SYNCREQUEST']._serialized_end=447
  _globals['_SYNCRESPONSE']._serialized_start=450
  _globals['_SYNCRESPONSE']._serialized_end=585
  _globals['_SYNCSERVICE']._serialized_start=587
  _globals['_SYNCSERVICE']._serialized_end=655
# @@protoc_insertion_point(module_scope)
