use textwrap;

/// Test text wrapping functionality for various types of content
#[test]
fn test_text_wrapping() {
    // Test case 1: Normal text with reasonable line length
    let normal_text = "This is a normal line of text that should wrap naturally at word boundaries.";
    
    // Test case 2: Text with very long words
    let long_word_text = "Thisisaverylongwordthatshouldbeforciblybrokenintomultiplelinesdespitenotcontaininganyspaces.";
    
    // Test case 3: Long run-on sentence without punctuation (like from ChatGPT)
    let long_runon_sentence = "This is a very long run on sentence that goes on and on and on and doesn't really have any natural breaking points so it should be wrapped by the system regardless of the fact that it continues for a very long time without giving any opportunity for natural wrapping at punctuation or other sentence breaks the kind that might be generated by an AI in response to a prompt that asks for a very long explanation of something complex";
    
    // Test case 4: Pre-formatted text with newlines (should be preserved)
    let preformatted_text = "Line 1\nLine 2\nLine 3\nA longer line that might need wrapping if it exceeds the width";
    
    // Configure wrapping with normal settings (80 chars)
    let normal_width = 80;
    let wrapped_normal = textwrap::wrap(normal_text, normal_width);
    
    // Should be a single line with this width
    assert_eq!(wrapped_normal.len(), 1);
    
    // Test with narrower width to force wrapping
    let narrow_width = 30;
    let wrapped_narrow = textwrap::wrap(normal_text, narrow_width);
    
    // Should be multiple lines with narrow width
    assert!(wrapped_narrow.len() > 1);
    
    // Configure specialized wrapping for long words and run-on sentences
    let options = textwrap::Options::new(40)
        .break_words(true);
    
    // Test wrapping the long word
    let wrapped_long_word = textwrap::fill(long_word_text, options)
        .lines()
        .map(|s| s.to_string())
        .collect::<Vec<String>>();
    
    // Should break the long word into multiple pieces
    assert!(wrapped_long_word.len() > 1);
    
    // Test wrapping the long run-on sentence
    let wrapped_runon = textwrap::fill(long_runon_sentence, options)
        .lines()
        .map(|s| s.to_string())
        .collect::<Vec<String>>();
    
    // Should have many lines
    assert!(wrapped_runon.len() > 5);
    
    // Make sure each line is no longer than our width
    for line in &wrapped_runon {
        assert!(line.len() <= 40);
    }
    
    // Test pre-formatted text handling
    let preformatted_lines = preformatted_text.lines().count();
    assert_eq!(preformatted_lines, 4);
    
    // When we identify text as pre-formatted, we should preserve line breaks
    // but still wrap long lines within each paragraph
    let preformatted_wrapped = preformatted_text
        .lines()
        .flat_map(|line| {
            textwrap::fill(line, options)
                .lines()
                .map(|s| s.to_string())
                .collect::<Vec<String>>()
        })
        .collect::<Vec<String>>();
    
    // Should have at least as many lines as the original
    assert!(preformatted_wrapped.len() >= preformatted_lines);
}

/// Test detection of pre-formatted text with newlines
#[test]
fn test_preformatted_text_detection() {
    // Test if text contains newlines (should be treated as pre-formatted)
    let text_with_newlines = "Line 1\nLine 2\nLine 3";
    assert!(text_with_newlines.contains('\n'));
    
    // Test Windows-style newlines
    let text_with_windows_newlines = "Line 1\r\nLine 2\r\nLine 3";
    assert!(text_with_windows_newlines.contains("\r\n"));
    
    // Text without newlines (should be wrapped normally)
    let text_without_newlines = "This is a single line of text without any newlines.";
    assert!(!text_without_newlines.contains('\n'));
    
    // In actual app code, we would use this condition:
    assert_eq!(text_with_newlines.contains('\n') || text_with_newlines.contains("\r\n"), true);
    assert_eq!(text_without_newlines.contains('\n') || text_without_newlines.contains("\r\n"), false);
}

/// Test the visual appearance of wrapped text to ensure it looks correct
#[test]
fn test_visual_wrapping() {
    // Create a mock console with a specific width
    let console_width = 40;
    
    // Test a paragraph that should wrap nicely
    let paragraph = "The quick brown fox jumps over the lazy dog. This is a paragraph that should wrap nicely at word boundaries.";
    
    // Wrap it with our settings
    let options = textwrap::Options::new(console_width)
        .break_words(true);
    
    let wrapped = textwrap::fill(paragraph, options)
        .lines()
        .map(|s| s.to_string())
        .collect::<Vec<String>>();
    
    // Expected result (manually verified to be reasonable)
    assert!(wrapped.len() >= 2); // Should be at least 2 lines
    
    // No line should exceed the console width
    for line in &wrapped {
        assert!(line.len() <= console_width as usize);
    }
    
    // Test a very long sentence
    let long_sentence = "Thisisaverylongsentencewithoutanyspacesorpunctuationthatshouldbeforcedtowrapatallavilableopportunitiesregardlessofwordbreaks";
    
    // Wrap it with our settings
    let wrapped_long = textwrap::fill(long_sentence, options)
        .lines()
        .map(|s| s.to_string())
        .collect::<Vec<String>>();
    
    // Should produce multiple lines
    assert!(wrapped_long.len() > 1);
    
    // No line should exceed the console width
    for line in &wrapped_long {
        assert!(line.len() <= console_width as usize);
    }
}

/// Integration test that simulates the actual wrapping logic in the application
#[test]
fn test_app_wrapping_logic() {
    // Mock UI width 
    let ui_width = 60;
    let padding = 2;
    let effective_width = ui_width - padding;
    
    // Test messages
    let messages = [
        "Short message that fits on one line",
        "This is a longer message that needs to be wrapped because it exceeds the UI width limit and should appear on multiple lines",
        "Thisisaverylongwordthatwillneedtobebrokenupintopieces",
        "Pre-formatted\nmessage\nwith\nnewlines",
        "This is an extremely long run-on sentence without proper punctuation or breaks the kind that might come from an AI attempting to explain a complex topic in response to a user query that asks for details about something intricate and requires an elaborate explanation that extends beyond what would normally fit within a simple line of text in a terminal UI and thus needs special handling to ensure it wraps properly",
    ];
    
    // Process each message according to our app logic
    for msg in &messages {
        // Detect if message is pre-formatted
        let is_preformatted = msg.contains('\n') || msg.contains("\r\n");
        
        if is_preformatted {
            // Handle pre-formatted text by preserving newlines but wrapping long lines
            let lines_count = msg.lines().count();
            assert!(lines_count > 1);
            
            // Each line in pre-formatted text should still be wrapped if too long
            for line in msg.lines() {
                let options = textwrap::Options::new(effective_width)
                    .break_words(true);
                
                let wrapped = textwrap::fill(line, options)
                    .lines()
                    .map(|s| s.to_string())
                    .collect::<Vec<String>>();
                
                for wrapped_line in &wrapped {
                    assert!(wrapped_line.len() <= effective_width as usize);
                }
            }
        } else {
            // Handle regular text with wrapping
            let options = textwrap::Options::new(effective_width)
                .break_words(true);
            
            let wrapped = textwrap::fill(msg, options)
                .lines()
                .map(|s| s.to_string())
                .collect::<Vec<String>>();
            
            // Check if wrapping behaves as expected
            if msg.len() > effective_width as usize {
                // Long message should be wrapped into multiple lines
                assert!(wrapped.len() > 1);
            }
            
            // No line should exceed the effective width
            for line in &wrapped {
                assert!(line.len() <= effective_width as usize);
            }
        }
    }
} 